# Generated by Django 2.2.2 on 2019-06-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('имя', models.CharField(max_length=25, verbose_name='Имя')),
                ('телефон', models.CharField(max_length=13, verbose_name='Телефон')),
                ('e_mail', models.CharField(max_length=25, verbose_name='E-mail')),
                ('текст', models.CharField(max_length=300, verbose_name='Сообщение')),
            ],
        ),
    ]
